### ISSUE TITLE
Crashes on some non-image files.

### ISSUE THREAD

**Issue by jeremymreed** [jeremymreed/image-file-name-fixer#1]
App is crashing on some non-image files, and dumping the following output to stdout:

```
❯ image-file-name-fixer --move --hash ./
/home/jeremyr/Downloads/config-old/foot/foot.ini: Unrecognized format
/home/jeremyr/Downloads/config-old/gammastep/config.ini: Unrecognized format
/home/jeremyr/Downloads/config-old/nordvpn/cli.log: Unrecognized format
/home/jeremyr/Downloads/config-old/nordvpn/nordvpn.conf: Unrecognized format
/home/jeremyr/Downloads/config-old/user-dirs.locale: Unrecognized format
/home/jeremyr/Downloads/config-old/lazygit/config.yml: Unrecognized format
/home/jeremyr/Downloads/config-old/lazygit/state.yml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/recentservers.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/filezilla.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/sitemanager.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/lockfile: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/trustedcerts.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/layout.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/queue.sqlite3: Unrecognized format
/home/jeremyr/Downloads/config-old/keepassxc/keepassxc.ini: Unrecognized format
/home/jeremyr/Downloads/config-old/user-dirs.dirs: Unrecognized format
/home/jeremyr/Downloads/config-old/broot/dark-gruvbox.hjson: Unrecognized format
/home/jeremyr/Downloads/config-old/broot/white-skin.hjson: Unrecognized format
thread 'main' panicked at src/processor.rs:84:48:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running with RUST_BACKTRACE=full:
```
❯ RUST_BACKTRACE=full image-file-name-fixer --move --hash ./ 
/home/jeremyr/Downloads/config-old/foot/foot.ini: Unrecognized format
/home/jeremyr/Downloads/config-old/gammastep/config.ini: Unrecognized format
/home/jeremyr/Downloads/config-old/nordvpn/cli.log: Unrecognized format
/home/jeremyr/Downloads/config-old/nordvpn/nordvpn.conf: Unrecognized format
/home/jeremyr/Downloads/config-old/user-dirs.locale: Unrecognized format
/home/jeremyr/Downloads/config-old/lazygit/config.yml: Unrecognized format
/home/jeremyr/Downloads/config-old/lazygit/state.yml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/recentservers.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/filezilla.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/sitemanager.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/lockfile: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/trustedcerts.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/layout.xml: Unrecognized format
/home/jeremyr/Downloads/config-old/filezilla/queue.sqlite3: Unrecognized format
/home/jeremyr/Downloads/config-old/keepassxc/keepassxc.ini: Unrecognized format
/home/jeremyr/Downloads/config-old/user-dirs.dirs: Unrecognized format
/home/jeremyr/Downloads/config-old/broot/dark-gruvbox.hjson: Unrecognized format
/home/jeremyr/Downloads/config-old/broot/white-skin.hjson: Unrecognized format
thread 'main' panicked at src/processor.rs:84:48:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x555a1585835c - <unknown>
   1:     0x555a1588078c - <unknown>
   2:     0x555a1585594e - <unknown>
   3:     0x555a15858144 - <unknown>
   4:     0x555a158597f3 - <unknown>
   5:     0x555a1585950c - <unknown>
   6:     0x555a15859d79 - <unknown>
   7:     0x555a15859c77 - <unknown>
   8:     0x555a15858886 - <unknown>
   9:     0x555a158599c2 - <unknown>
  10:     0x555a1563efa3 - <unknown>
  11:     0x555a1563f3aa - <unknown>
  12:     0x555a156aafb3 - <unknown>
  13:     0x555a156aa1f1 - <unknown>
  14:     0x555a156aa1f1 - <unknown>
  15:     0x555a156aa1f1 - <unknown>
  16:     0x555a156aa1f1 - <unknown>
  17:     0x555a156aa1f1 - <unknown>
  18:     0x555a156d3046 - <unknown>
  19:     0x555a15682f83 - <unknown>
  20:     0x555a156b2b79 - <unknown>
  21:     0x555a15850c2b - <unknown>
  22:     0x555a156d30b5 - <unknown>
  23:     0x7fcee6962cd0 - <unknown>
  24:     0x7fcee6962d8a - __libc_start_main
  25:     0x555a1563f625 - <unknown>
  26:                0x0 - <unknown>
```

**Comment by jeremymreed** [comment]
I think you've seen this before.  Check debugging output, and see exactly which file is triggering this error.

**Comment by jeremymreed** [comment]
Workaround by putting images in `~/Downloads/Images` before processing them with this tool.
